import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json());

  // Initialize GoogleGenAI
  const apiKey = process.env.GEMINI_API_KEY;
  const ai = new GoogleGenAI({
    apiKey: apiKey,
    httpOptions: {
      headers: {
        'User-Agent': 'aistudio-build',
      }
    }
  });

  // API endpoint for generating lifecycle map
  app.post("/api/generate", async (req, res) => {
    try {
      const { idea } = req.body;
      if (!idea || typeof idea !== "string" || idea.trim().length === 0) {
        return res.status(400).json({ error: "Please provide a valid project idea." });
      }

      if (!apiKey) {
        return res.status(500).json({
          error: "GEMINI_API_KEY environment variable is not defined. Please add your key in Settings > Secrets."
        });
      }

      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: `Project Idea: ${idea}`,
        config: {
          systemInstruction: "You are an Elite Technical Project Manager. Take the user's raw idea and break it down into exactly 5 chronologically ordered tasks representing a healthy project development lifecycle:\n1. Planning & Setup\n2. Design & Layout\n3. Building & Coding\n4. Testing & Fixing\n5. Launching & Supporting\nWrite everything using extremely simple, clear, everyday language that is easy for anyone to understand without technical jargon or complex words. Each task must have: a sequence number, a distinct easy-to-understand category representing its respective lifecycle step, a clear simple actionable Title, and a 2-sentence descriptive breakdown of how to execute it simply.",
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                sequence: {
                  type: Type.INTEGER,
                  description: "The sequence order of the task, from 1 to 5.",
                },
                category: {
                  type: Type.STRING,
                  description: "A very simple, easy-to-understand category name, e.g., Rules & Permits, Setup & Gear, Website & Code, Customers & Ads, Safety & Checks.",
                },
                title: {
                  type: Type.STRING,
                  description: "A very clear, simple, and action-oriented title.",
                },
                breakdown: {
                  type: Type.STRING,
                  description: "A clear and simple 2-sentence description of what needs to be done and how to do it.",
                }
              },
              required: ["sequence", "category", "title", "breakdown"]
            }
          }
        }
      });

      const responseText = response.text;
      if (!responseText) {
        throw new Error("No output was generated by the AI model. Check if your API key balances or permissions allow this model.");
      }

      const tasks = JSON.parse(responseText);
      return res.json({ tasks });

    } catch (error: any) {
      console.error("AI Generation Error:", error);
      return res.status(500).json({
        error: error?.message || "Failed to generate project lifecycle map. Please try again."
      });
    }
  });

  // Service static assets or mount Vite dev server
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on host 0.0.0.0, port ${PORT}`);
  });
}

startServer();
